#!/bin/bash
machine=`uname -n | cut -c1-4`
if [ "$machine" == 'cori' ]; then
	CC='ftn'
else
	CC='mpifort'
fi
$CC -c -O3 beam_mod.f90 parallel_mod.f90 liea_mod.f90
$CC -c -O3 book.f comm1.f liea.f elem.f sss.f pcmap.f set_pscale.f  base.f math.f hamdrift.f cex.f genm.f pure.f hmltn12345.f sbend.f trac.f
mv *.o ../
mv *.mod ../
